# Site settings
title: Marrony Neris personal blog
email: neris.marrony@gmail.com
description: >
  Here I'll try to post things related to sofware development, computer graphics, game development or anything related to technology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marrony.github.io" # the base hostname & protocol for your site
#twitter_username: none
github_username:  marrony
linkedin_username: marrony

# Build settings
markdown: kramdown
